---
apiVersion: v2
appVersion: "v1.1.2"
version: 0.2.3
name: clarkson
description: A web-based dashboard application that gives you a neat and clean interface for logging your fuel fill-ups for all of your vehicles.
type: application
home: "https://github.com/nicholaswilde/helm-charts/tree/main/charts/clarkson"
icon: "https://github.com/linuxserver/Clarkson/raw/master/src/mstile-150x150.png"
dependencies:
  - name: common
    version: ~0.1.13
    repository: https://nicholaswilde.github.io/helm-charts/
  - name: mariadb
    version: ~1.0.3
    repository: https://nicholaswilde.github.io/helm-charts/
    condition: mariadb.enabled
keywords:
  - fuel
  - car
  - log
  - fill-up
  - vehicle
sources:
  - https://github.com/linuxserver/Clarkson
  - https://hub.docker.com/r/linuxserver/clarkson
maintainers:
  - name: nicholaswilde
    email: ncwilde43@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Change image tag to version-v1.1.2 to reduce number of chart releases.
  artifacthub.io/images: |
    - name: clarkson
      image: ghcr.io/linuxserver/clarkson:version-v1.1.2
