---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/linuxserver/snipe-it
  pullPolicy: IfNotPresent
  tag: "version-v5.1.8"

secret: {}
  # MYSQL_ROOT_PASSWORD: snipe-it-pass
  # MYSQL_PASSWORD: snipe-it-pass

# See more environment variables in the snipe documentation
# https://github.com/linuxserver/docker-snipe-it#parameters
env: {}
  # NGINX_APP_URL: "192.168.1.206:8080"
  # MYSQL_USER: snipe-it
  # MYSQL_DATABASE: "snipe-it-mariadb"
  # MYSQL_PORT_3306_TCP_ADDR: "snipe-it-mariadb"
  # MYSQL_PORT_3306_TCP_PORT: "3306"

service:
  main:
    ports:
      main:
        port: 80

ingress:
  enabled: false

persistence:
  config:
    enabled: false
    mountPath: /config
    accessMode: ReadWriteOnce

# Enable mariadb
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/mariadb/values.yaml
mariadb:
  enabled: false
  secret:
    MYSQL_ROOT_PASSWORD: snipe-it-pass
    MYSQL_PASSWORD: snipe-it-pass
  env:
    MYSQL_DATABASE: snipe-it-mariadb
    MYSQL_USER: snipe-it
  fullnameOverride: snipe-it-mariadb
