---
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

image:
  repository: ghcr.io/nicholaswilde/chyrp-lite
  pullPolicy: IfNotPresent
  tag: "version-v2021.03"

# See more environment variables in the chyrp-lite documentation
# https://github.com/nicholaswilde/docker-chyrp-lite
env: {}
  # TZ: "America/Los_Angeles"

service:
  main:
    ports:
      main:
        port: 80

ingress:
  enabled: false

persistence:
  data:
    enabled: false
    mountPath: /data
    accessMode: ReadWriteOnce
    size: 1Gi
  html:
    enabled: false
    mountPath: /var/www/html
    accessMode: ReadWriteOnce
    size: 1Gi
