image:
  repository: ghcr.io/nicholaswilde/blog
  pullPolicy: IfNotPresent
  tag: "version-v1.3"

secret:
  BLOG_NICK: username
  BLOG_PASS: password

# See more environment variables in the blog documentation
# https://github.com/nicholaswilde/docker-blog
env:
  TZ: "America/Los_Angeles"
  BLOG_TITLE: Blog
  BLOG_NAME: Max Musermann
  BLOG_LANG: en

service:
  main:
    ports:
      main:
        port: 80

ingress:
  enabled: false

persistence:
  data:
    enabled: false
    mountPath: /var/www/html/data
    accessMode: ReadWriteOnce
    size: 1Gi
